name: auto_brightness
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  flutter: 
    sdk: flutter
  light: ^2.1.0
  udp: ^5.0.3
  win32: ^2.6.1
  wakelock: ^0.6.1+2
  screen_brightness: ^0.2.1
  tray_manager: ^0.1.8
  bitsdojo_window: ^0.1.2
  process_run: ^0.12.3+2
  launch_at_startup: ^0.1.7
  syncfusion_flutter_sliders: ^20.1.61
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  belatuk_http_server: ^2.1.0
  dio: ^4.0.6
  fullscreen: ^1.0.3
  analog_clock: ^0.1.0
  oktoast: ^3.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
