name: auto_brightness
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  flutter: 
    sdk: flutter
  light: ^2.1.0
  udp: ^5.0.3
  win32: ^2.6.1
  wakelock: ^0.6.1+2
  screen_brightness: ^0.2.1
  flutter_advanced_seekbar: ^0.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

