app_id: A9847403-5E0B-0853-1FB6-A64A034AA59E
publisher: yang
publisher_url: https://github.com/Siriusyy/auto_brightness
display_name: Auto Brightness
create_desktop_icon: true
install_dir_name: AutoBrightness