name: Build Windows Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          cache: true
          architecture: x64


      - name: Build Windows Release
        run: |
          dart pub global activate flutter_distributor
          flutter_distributor package --platform=windows --targets=exe

      - name: Upload EXE artifact
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.get-release.outputs.upload_url }}
          asset_path: dist/*/*
          overwrite: true
